easy_admin:
  entities:
#        # List the entity class name you want to manage
    - App\Entity\User
    - App\Entity\Animal
    - App\Entity\FA
    - App\Entity\Membre
    - App\Entity\Gerant
    - App\Entity\Donation
    - App\Entity\Race
    - App\Entity\Event



